name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
 
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
         
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mixnode:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mixnode:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mixnode:buildcache,mode=max

    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

